/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VE.GUI;

import RMI.RMI;
import RMI.Remote;
import VE.core.Block;
import VE.core.Ledger;
import VE.core.Vote;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;

/**
 *
 * @author andre
 */
public class GUI extends javax.swing.JFrame {

    public static final String fileVote = "BVote.txt";
    Ledger Vote;
    Block newBlock;
    Remote node; 
    /**
     * Creates new form EVGUI
     */
    public GUI() {
        try {
            initComponents();
            Vote = new Ledger();
            Vote = Ledger.load(fileVote);
            showLedger();
        } catch (Exception ex) {
            showExceptionError(ex);
        }

    }

    private void showExceptionError(Exception ex) {
        JOptionPane.showMessageDialog(this,
                ex.getMessage(), ex.getClass().getSimpleName(), JOptionPane.ERROR_MESSAGE);
        Logger.getLogger(Vote.class.getName()).log(Level.SEVERE, null, ex);
    }

    private void showLedger() {
        DefaultListModel model = new DefaultListModel();
        model.addAll(Vote.getHistory());
        lstLedger.setModel(model);

    }
    
    private void isInFile(String book) throws FileNotFoundException, IOException, Exception{
        FileReader fileR = new FileReader("BVote.txt");
        BufferedReader reader = new BufferedReader(fileR);
        String readvc = reader.readLine();
        while (readvc != null) {
            if (readvc.contains(book)) {
               throw new Exception ("Já foi feito um voto");
            }
            readvc = reader.readLine();
        }
         Vote v = new Vote(
                    newBlock.toString(),
                    btnsPartidos.getSelection().getActionCommand());
            Vote.add(v);
            Vote.saveFile(fileVote);
} 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnsPartidos = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        CC = new javax.swing.JLabel();
        txtNumCC = new javax.swing.JTextField();
        listaPartidos = new javax.swing.JLabel();
        Votar = new javax.swing.JButton();
        PS = new javax.swing.JRadioButton();
        PSD = new javax.swing.JRadioButton();
        CDS = new javax.swing.JRadioButton();
        PCP = new javax.swing.JRadioButton();
        BE = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstLedger = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        spMyServerPort = new javax.swing.JSpinner();
        btStartServer = new javax.swing.JButton();
        dificulty = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CC.setText("Número de CC");

        txtNumCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumCCActionPerformed(evt);
            }
        });

        listaPartidos.setText("Lista de Partidos");

        Votar.setText("Votar");
        Votar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VotarActionPerformed(evt);
            }
        });

        btnsPartidos.add(PS);
        PS.setText("PS");
        PS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PSActionPerformed(evt);
            }
        });

        btnsPartidos.add(PSD);
        PSD.setText("PSD");
        PSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PSDActionPerformed(evt);
            }
        });

        btnsPartidos.add(CDS);
        CDS.setText("CDS-PP");
        CDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CDSActionPerformed(evt);
            }
        });

        btnsPartidos.add(PCP);
        PCP.setText("PCP");
        PCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PCPActionPerformed(evt);
            }
        });

        btnsPartidos.add(BE);
        BE.setText("BE");
        BE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(CC, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtNumCC, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(listaPartidos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Votar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(PS, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(PSD, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(CDS, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(PCP, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(BE, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumCC, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CC))
                        .addGap(167, 167, 167)
                        .addComponent(listaPartidos))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CDS, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PCP, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BE, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PS, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PSD, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Votar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(293, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(listaPartidos)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(CC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(PS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PSD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CDS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PCP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BE)
                .addGap(55, 55, 55)
                .addComponent(Votar)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Client", jPanel1);

        lstLedger.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        lstLedger.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstLedger.setPreferredSize(new java.awt.Dimension(450, 300));
        jScrollPane1.setViewportView(lstLedger);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        spMyServerPort.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        spMyServerPort.setModel(new javax.swing.SpinnerNumberModel(1010, 1010, null, 1));
        spMyServerPort.setBorder(javax.swing.BorderFactory.createTitledBorder("Port"));

        btStartServer.setText("Start Server");
        btStartServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStartServerActionPerformed(evt);
            }
        });

        jLabel1.setText("Dificuldade");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spMyServerPort, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btStartServer, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dificulty)
                            .addComponent(jLabel1))))
                .addGap(118, 118, 118))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(spMyServerPort, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(btStartServer, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dificulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Server", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btStartServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStartServerActionPerformed
        try {

            spMyServerPort.setVisible(false);
            btStartServer.setVisible(false);
            int port = (int) spMyServerPort.getValue();
            node = new Remote(port);

            node.addListener(listeners);

            RMI.startRemoteObject(node, port, Remote.remoteName);
            logMessage(node.getAdress());
            jTextArea1.setText(spMyServerPort.getValue().toString());

        } catch (Exception ex) {
            logError(ex.getMessage());
        }
    }//GEN-LAST:event_btStartServerActionPerformed

    private void BEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEActionPerformed
        // TODO add your handling code here:
        BE.setActionCommand("BE");
    }//GEN-LAST:event_BEActionPerformed

    private void PCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PCPActionPerformed
        // TODO add your handling code here:
        PS.setActionCommand("PCP");
    }//GEN-LAST:event_PCPActionPerformed

    private void CDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CDSActionPerformed
        // TODO add your handling code here:
        CDS.setActionCommand("CDS");
    }//GEN-LAST:event_CDSActionPerformed

    private void PSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PSDActionPerformed
        // TODO add your handling code here:
        PSD.setActionCommand("PSD");
    }//GEN-LAST:event_PSDActionPerformed

    private void PSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PSActionPerformed
        // TODO add your handling code here:
        PS.setActionCommand("PS");
    }//GEN-LAST:event_PSActionPerformed

    private void VotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VotarActionPerformed
        try {
            newBlock = new Block("0000",
                txtNumCC.getText(),
                Integer.valueOf(dificulty.getText()));
            newBlock.startMine();
            jTextArea1.setText(newBlock.toString());
            /*Vote v = new Vote(
                newBlock.toString(),
                btnsPartidos.getSelection().getActionCommand());
            Vote.add(v);
            Vote.saveFile(fileVote);*/
            isInFile(newBlock.toString());
            showLedger();

        } catch (Exception ex) {
            showExceptionError(ex);
        }
    }//GEN-LAST:event_VotarActionPerformed

    private void txtNumCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumCCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BE;
    private javax.swing.JLabel CC;
    private javax.swing.JRadioButton CDS;
    private javax.swing.JRadioButton PCP;
    private javax.swing.JRadioButton PS;
    private javax.swing.JRadioButton PSD;
    private javax.swing.JButton Votar;
    private javax.swing.JButton btStartServer;
    private javax.swing.ButtonGroup btnsPartidos;
    private javax.swing.JTextField dificulty;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel listaPartidos;
    private javax.swing.JList<String> lstLedger;
    private javax.swing.JSpinner spMyServerPort;
    private javax.swing.JTextField txtNumCC;
    // End of variables declaration//GEN-END:variables

    private void logError(String message) {
        printLog(message);
    }

    private void logMessage(String adress) {
       printLog(adress);
    }
    
     private void printLog(String message) {
            /*@Override
            public void run() {*/
               
              
                jTextArea1.setCaretPosition(0);
             
                jTextArea1.replaceSelection(" " + message);
                jTextArea1.setCaretPosition(0);
               
            }
}
