/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VE.GUI;

import VE.core.Block;
import VE.core.Ledger;
import VE.core.Vote;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author andre
 */
public class GUI extends javax.swing.JFrame {

    Block myBlock;
    public static final String fileVote = "BVote.txt";
    Ledger Vote;

    /**
     * Creates new form EVGUI
     */
    public GUI() {
       try {
            initComponents();
            Vote = new Ledger();
            Vote = Ledger.load(fileVote);
            showLedger();
        } catch (Exception ex) {
            showExceptionError(ex);
        }
    }

    private void showExceptionError(Exception ex) {
        JOptionPane.showMessageDialog(this,
                ex.getMessage(), ex.getClass().getSimpleName(), JOptionPane.ERROR_MESSAGE);
        Logger.getLogger(Vote.class.getName()).log(Level.SEVERE, null, ex);
    }

    private void showLedger() {
        DefaultListModel model = new DefaultListModel();
        model.addAll(Vote.getHistory());
        lstLedger.setModel(model);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnsPartidos = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        CC = new javax.swing.JLabel();
        txtNumCC = new javax.swing.JTextField();
        listaPartidos = new javax.swing.JLabel();
        Votar = new javax.swing.JButton();
        PS = new javax.swing.JRadioButton();
        PSD = new javax.swing.JRadioButton();
        CDS = new javax.swing.JRadioButton();
        PCP = new javax.swing.JRadioButton();
        BE = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jsDificulty = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstLedger = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        CC1 = new javax.swing.JLabel();
        txtNumCC1 = new javax.swing.JTextField();
        listaPartidos1 = new javax.swing.JLabel();
        Votar1 = new javax.swing.JButton();
        PS1 = new javax.swing.JRadioButton();
        PSD1 = new javax.swing.JRadioButton();
        CDS1 = new javax.swing.JRadioButton();
        PCP1 = new javax.swing.JRadioButton();
        BE1 = new javax.swing.JRadioButton();
        dificulty1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstLedger1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CC.setText("Número de CC");

        txtNumCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumCCActionPerformed(evt);
            }
        });

        listaPartidos.setText("Lista de Partidos");

        Votar.setText("Votar");
        Votar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VotarActionPerformed(evt);
            }
        });

        btnsPartidos.add(PS);
        PS.setText("PS");
        PS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PSActionPerformed(evt);
            }
        });

        btnsPartidos.add(PSD);
        PSD.setText("PSD");
        PSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PSDActionPerformed(evt);
            }
        });

        btnsPartidos.add(CDS);
        CDS.setText("CDS-PP");
        CDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CDSActionPerformed(evt);
            }
        });

        btnsPartidos.add(PCP);
        PCP.setText("PCP");
        PCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PCPActionPerformed(evt);
            }
        });

        btnsPartidos.add(BE);
        BE.setText("BE");
        BE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEActionPerformed(evt);
            }
        });

        jLabel1.setText("Dificuldade");

        jDesktopPane1.setLayer(CC, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtNumCC, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(listaPartidos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Votar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(PS, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(PSD, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(CDS, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(PCP, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(BE, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jsDificulty, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumCC, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CC))
                        .addGap(57, 57, 57)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jsDificulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(Votar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CDS, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PCP, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BE, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PS, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PSD, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(listaPartidos)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CC)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsDificulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(listaPartidos)
                .addGap(18, 18, 18)
                .addComponent(PS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PSD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CDS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PCP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(Votar)
                .addContainerGap())
        );

        lstLedger.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        lstLedger.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstLedger.setPreferredSize(new java.awt.Dimension(450, 300));
        jScrollPane1.setViewportView(lstLedger);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jDesktopPane1))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Client", jPanel1);

        CC1.setText("Número de CC");

        txtNumCC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumCC1ActionPerformed(evt);
            }
        });

        listaPartidos1.setText("Lista de Partidos");

        Votar1.setText("Votar");
        Votar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Votar1ActionPerformed(evt);
            }
        });

        btnsPartidos.add(PS1);
        PS1.setText("PS");
        PS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PS1ActionPerformed(evt);
            }
        });

        btnsPartidos.add(PSD1);
        PSD1.setText("PSD");
        PSD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PSD1ActionPerformed(evt);
            }
        });

        btnsPartidos.add(CDS1);
        CDS1.setText("CDS-PP");
        CDS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CDS1ActionPerformed(evt);
            }
        });

        btnsPartidos.add(PCP1);
        PCP1.setText("PCP");
        PCP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PCP1ActionPerformed(evt);
            }
        });

        btnsPartidos.add(BE1);
        BE1.setText("BE");
        BE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BE1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Dificuldade");

        jDesktopPane2.setLayer(CC1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(txtNumCC1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(listaPartidos1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(Votar1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(PS1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(PSD1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(CDS1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(PCP1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(BE1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(dificulty1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumCC1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CC1))
                        .addGap(57, 57, 57)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dificulty1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(Votar1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CDS1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PCP1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BE1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PS1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PSD1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(listaPartidos1)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CC1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumCC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dificulty1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(listaPartidos1)
                .addGap(18, 18, 18)
                .addComponent(PS1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PSD1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CDS1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PCP1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BE1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(Votar1)
                .addContainerGap())
        );

        lstLedger1.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        lstLedger1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstLedger1.setPreferredSize(new java.awt.Dimension(450, 300));
        jScrollPane2.setViewportView(lstLedger1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jDesktopPane2))
                .addGap(91, 91, 91))
        );

        jTabbedPane1.addTab("Server", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumCC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumCC1ActionPerformed
        txtNumCC1.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char caracter = e.getKeyChar();
                if (((caracter < '0') || (caracter > '9'))
                        && (caracter != '\b')) {
                    e.consume();
                }
            }
        });
    }//GEN-LAST:event_txtNumCC1ActionPerformed

    private void Votar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Votar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Votar1ActionPerformed

    private void PS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PS1ActionPerformed

    private void PSD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PSD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PSD1ActionPerformed

    private void CDS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CDS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CDS1ActionPerformed

    private void PCP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PCP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PCP1ActionPerformed

    private void BE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BE1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BE1ActionPerformed

    private void VotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VotarActionPerformed
        
        try {
            myBlock = new Block(txtNumCC.getText(),btnsPartidos.getSelection().getActionCommand());
            myBlock.mine((Integer) jsDificulty.getValue());
            Vote.saveFile(fileVote);
            showLedger();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),
                    "Alert", JOptionPane.WARNING_MESSAGE);
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        /*try {
            Vote v = new Vote(
                    Integer.valueOf(txtNumCC.getText()),
                    btnsPartidos.getSelection().getActionCommand(),
                    Integer.valueOf(dificulty.getText()));
            Vote.add(v);
            Vote.saveFile(fileVote);
            showLedger();
           
       
    }//GEN-LAST:event_VotarActionPerformed

    private void txtNumCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumCCActionPerformed

    private void BEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEActionPerformed
        // TODO add your handling code here:
        BE.setActionCommand("BE");
    }//GEN-LAST:event_BEActionPerformed

    private void PCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PCPActionPerformed
        // TODO add your handling code here:
        PS.setActionCommand("PCP");
    }//GEN-LAST:event_PCPActionPerformed

    private void CDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CDSActionPerformed
        // TODO add your handling code here:
        CDS.setActionCommand("CDS");
    }//GEN-LAST:event_CDSActionPerformed

    private void PSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PSDActionPerformed
        // TODO add your handling code here:
        PSD.setActionCommand("PSD");
    }//GEN-LAST:event_PSDActionPerformed

    private void PSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PSActionPerformed
        // TODO add your handling code here:
        PS.setActionCommand("PS");
    }//GEN-LAST:event_PSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BlockMine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BlockMine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BlockMine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BlockMine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BE;
    private javax.swing.JRadioButton BE1;
    private javax.swing.JLabel CC;
    private javax.swing.JLabel CC1;
    private javax.swing.JRadioButton CDS;
    private javax.swing.JRadioButton CDS1;
    private javax.swing.JRadioButton PCP;
    private javax.swing.JRadioButton PCP1;
    private javax.swing.JRadioButton PS;
    private javax.swing.JRadioButton PS1;
    private javax.swing.JRadioButton PSD;
    private javax.swing.JRadioButton PSD1;
    private javax.swing.JButton Votar;
    private javax.swing.JButton Votar1;
    private javax.swing.ButtonGroup btnsPartidos;
    private javax.swing.JTextField dificulty1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSpinner jsDificulty;
    private javax.swing.JLabel listaPartidos;
    private javax.swing.JLabel listaPartidos1;
    private javax.swing.JList<String> lstLedger;
    private javax.swing.JList<String> lstLedger1;
    private javax.swing.JTextField txtNumCC;
    private javax.swing.JTextField txtNumCC1;
    // End of variables declaration//GEN-END:variables

}
